[server]
headless = true
address = "0.0.0.0"
port = 3002
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false
maxUploadSize = 500
maxMessageSize = 500

[browser]
gatherUsageStats = false
